# _config.yml
title: My Slate Themed Site
description: A simple static site using the Slate theme
theme: jekyll-theme-slate
baseurl: "" # Leave empty if using at the root of the GitHub Pages
url: "https://your-username.github.io" # Your GitHub Pages URL

# Optional navigation configuration (if you are manually setting up a navbar)
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Blog"
    url: "/blog/"
