# _config.yml
title: My Slate Themed Site
description: A simple static site using the Slate theme
theme: jekyll-theme-slate
baseurl: "/transit-ad"  # Replace with your repository name
url: "https://hnfontenot.github.io"  # Your GitHub Pages URL

# Optional navigation configuration (if you are manually setting up a navbar)
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Blog"
    url: "/blog/"
